### ISSUE TITLE
好像不支持tls_only的配置

### ISSUE THREAD

**Issue by fulyaec** [luckjiawei/frpc-desktop#25]
### 🖥️ 操作系统：
windows
### 🔖 版本号：
1.0.9
### 🤔 问题描述：
好像不支持`tls_only`的配置？我在服务端使用了`tls_only=true`后，使用`frpc-desktop`连接不上。看了下日志，没有把配置写到`frp.ini`。
### 🔊 日志：

> 日志目录:
* Window: `%APPDATA%\Frpc-Desktop\logs\`
* MacOS: `~/Library/Logs/Frpc-Desktop/logs/`
* Linux: `~/Library/Logs/Frpc-Desktop/`

**Comment by luckjiawei** [comment]
有这个参数吗？
我在frp中没有找到 https://github.com/fatedier/frp/blob/v0.51.3/conf/frpc_full.ini

**Comment by fulyaec** [comment]
> 有这个参数吗？ 我在frp中没有找到 https://github.com/fatedier/frp/blob/v0.51.3/conf/frpc_full.ini

有的，在这个文件里面<https://github.com/fatedier/frp/blob/v0.51.3/conf/frps_full.ini>

**Comment by luckjiawei** [comment]
你是服务端开启了tls 客户端没有配置tls对应的配置导致连不上
对应的客户端配置：
```toml
tls_enable = true

tls_cert_file = client.crt
tls_key_file = client.key
tls_trusted_ca_file = ca.crt
tls_server_name = example.com
```

这部分配置已可以可视化配置

<img width="800" alt="image" src="https://github.com/user-attachments/assets/df6c3513-295a-46c7-aaa6-0fee4ddf50f9">
