### ISSUE TITLE
Require `locations` field for URL Routing

### ISSUE THREAD

**Issue by daviddwlee84** [luckjiawei/frpc-desktop#81]
According to the [FRP URL Routing guide](https://github.com/fatedier/frp?tab=readme-ov-file#url-routing)

We should be able to setup multiple web proxy by different locations like this

```toml
# frpc.toml

[[proxies]]
name = "web01"
type = "http"
localPort = 80
customDomains = ["web.example.com"]
locations = ["/"]

[[proxies]]
name = "web02"
type = "http"
localPort = 81
customDomains = ["web.example.com"]
locations = ["/news", "/about"]
```

Maybe we can have *location* field when we are setting "http" type (below the *custom subdomain* setting)

![Image](https://github.com/user-attachments/assets/0fc59507-6c70-4383-aa28-fd0c4dfa309e)
